version: "3.3"
services:
  ubuntu1804:
    build:
      context: .
      dockerfile: Dockerfile
    image: ubuntu1804image
    container_name: ubuntu1804container
    volumes:
      - type: bind
        source: ./workspace
        target: /workspace
    stdin_open: true
    tty: true
    working_dir: /workspace
    ports:
      - "37564:37564/udp"
    
    # to use gdb (Warning! Take care of its low security. )
    # Ref: https://qiita.com/dbgso/items/6e2f317d6d13bdc387f8
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
